### ISSUE TITLE
Postgres schemas

### ISSUE THREAD

**Issue by jordic** [guillotinaweb/guillotina_dynamictablestorage#1]
What do you think about adding support for postgres schemas, also? For our use case will allow us to have the same db, with al benefits (reusing connection pools) and having a separation of concerns about the different app parts.

**Comment by vangheem** [comment]
Can you explain more about what you mean here?

**Comment by jordic** [comment]
yup, of course!
Instead of namespace tables, be able to just define the storage on a postgres schema:
```
storages:
  my-storage:
    storage: postgresql
    schema: my_storage
    dsn: postgresql://postgres@localhost:5432/guillotina
  second:
    storage: postgresql
    schema: second
    dsn: postgresql://postgres@localhost:5432/guillotina
```

Thought it's the same resut as namespaced tables.
